# Generated by Django 5.0.9 on 2026-07-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('new_customers_count', models.PositiveIntegerField(default=0)),
                ('visitors_count', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='stores.store')),
            ],
            options={
                'db_table': 'analytics_snapshot',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='analyticssnapshot',
            constraint=models.UniqueConstraint(fields=('store', 'date'), name='unique_snapshot_per_store_per_day'),
        ),
    ]
