services:
  - type: web
    name: komi-backend
    runtime: python
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.13.14"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_PROVIDER
        value: resend
      - key: RESEND_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: STORE_DOMAIN_SUFFIX
        sync: false
      - key: JWT_ACCESS_TOKEN_LIFETIME_MINUTES
        value: "30"
      - key: JWT_REFRESH_TOKEN_LIFETIME_DAYS
        value: "7"
      - key: FEDAPAY_PUBLIC_KEY
        sync: false
      - key: FEDAPAY_SECRET_KEY
        sync: false
      - key: FEDAPAY_ENVIRONMENT
        sync: false
      - key: FEDAPAY_WEBHOOK_SECRET
        sync: false
      - key: AI_PROVIDER
        value: groq
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
