# Generated by Django 5.0.9 on 2026-07-17 21:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('new_order', 'Nouvelle commande'), ('order_confirmed', 'Commande confirmée'), ('order_cancelled', 'Commande annulée'), ('product_added', 'Produit ajouté'), ('product_deleted', 'Produit supprimé'), ('low_stock', 'Stock faible'), ('store_published', 'Boutique publiée'), ('welcome', 'Bienvenue'), ('system', 'Système')], default='system', max_length=32)),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stores.store')),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'is_read'], name='notificatio_store_i_cbea03_idx')],
            },
        ),
    ]
