# Generated by Django 5.0.9 on 2026-07-17 21:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accent_color', models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #6C5CE7.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('font_family', models.CharField(choices=[('inter', 'Inter'), ('poppins', 'Poppins'), ('manrope', 'Manrope'), ('sora', 'Sora'), ('work_sans', 'Work Sans')], default='inter', max_length=16)),
                ('show_hero_banner', models.BooleanField(default=True)),
                ('show_social_links', models.BooleanField(default=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='stores.store')),
            ],
            options={
                'db_table': 'themes_store_theme',
            },
        ),
    ]
