# Generated by Django 5.0.9 on 2026-07-18 11:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='stores.store')),
            ],
            options={
                'db_table': 'wallets_wallet',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('method', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('celtiis_cash', 'Celtiis Cash')], max_length=20)),
                ('mobile_number', models.CharField(max_length=32)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Refusé')], default='pending', max_length=16)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='stores.store')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallets.wallet')),
            ],
            options={
                'db_table': 'wallets_withdrawal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('payment_received', 'Paiement reçu'), ('order_cancelled', 'Commande annulée'), ('refund', 'Remboursement'), ('withdrawal_requested', 'Retrait demandé'), ('withdrawal_approved', 'Retrait validé'), ('withdrawal_rejected', 'Retrait refusé'), ('adjustment', 'Ajustement')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='completed', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: positive credits, negative debits.', max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='payments.payment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='wallets.withdrawal')),
            ],
            options={
                'db_table': 'wallets_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['store', 'status'], name='wallets_wit_store_i_d4eba4_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'type'], name='wallets_tra_wallet__79bd45_idx'),
        ),
    ]
