# Generated by Django 5.0.9 on 2026-07-19 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('queued', "En file d'attente"), ('sent', 'Envoyé'), ('failed', 'Échoué')], default='queued', max_length=16)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'emails_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='emails_log_status_c5fd1c_idx')],
            },
        ),
    ]
