# Generated by Django 5.0.9 on 2026-07-18 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('scope', models.CharField(choices=[('merchant', 'Commerçant'), ('buyer', 'Acheteur')], max_length=16)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Comy')], max_length=16)),
                ('content', models.TextField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation')),
            ],
            options={
                'db_table': 'ai_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('health_score', models.PositiveIntegerField()),
                ('stats_snapshot', models.JSONField(default=dict)),
                ('tips', models.JSONField(default=list)),
                ('narrative', models.TextField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_daily_briefings', to='stores.store')),
            ],
            options={
                'db_table': 'ai_daily_briefing',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['store', 'scope', 'session_key'], name='ai_conversa_store_i_f3d3c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailybriefing',
            constraint=models.UniqueConstraint(fields=('store', 'date'), name='unique_briefing_per_store_per_day'),
        ),
    ]
