# Generated by Django 5.0.9 on 2026-07-19 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(choices=[('health_explain', 'Explication du score de santé'), ('daily_briefing', 'Briefing quotidien'), ('product_analysis', 'Analyse produit'), ('merchant_chat', 'Chat commerçant'), ('buyer_chat', 'Chat acheteur')], max_length=32)),
                ('cache_hit', models.BooleanField(default=False)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_usage_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', 'created_at'], name='ai_usage_lo_feature_d9c96a_idx')],
            },
        ),
    ]
