# Generated by Django 5.0.9 on 2026-07-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=8)),
                ('logger_name', models.CharField(max_length=150)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'backoffice_system_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='backoffice__level_33613d_idx')],
            },
        ),
    ]
