# Generated by Django 5.0.9 on 2026-07-17 21:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(choices=[('clothing', 'Vêtements'), ('shoes', 'Chaussures'), ('cosmetics', 'Cosmétiques'), ('perfumes', 'Parfums'), ('phones', 'Téléphones'), ('accessories', 'Accessoires'), ('restaurant', 'Restaurant'), ('pastry', 'Pâtisserie'), ('electronics', 'Électronique'), ('beauty', 'Beauté'), ('services', 'Services'), ('crafts', 'Artisanat'), ('other', 'Autre')], default='other', max_length=32)),
                ('country', models.CharField(choices=[('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('CM', 'Cameroun'), ('NG', 'Nigeria'), ('GH', 'Ghana'), ('BJ', 'Bénin'), ('TG', 'Togo'), ('ML', 'Mali'), ('BF', 'Burkina Faso'), ('CD', 'RD Congo'), ('CG', 'Congo'), ('GA', 'Gabon'), ('KE', 'Kenya'), ('ZA', 'Afrique du Sud'), ('MA', 'Maroc'), ('EG', 'Égypte'), ('OTHER', 'Autre')], max_length=8)),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (XOF)'), ('XAF', 'Franc CFA (XAF)'), ('NGN', 'Naira (NGN)'), ('GHS', 'Cedi (GHS)'), ('KES', 'Shilling (KES)'), ('ZAR', 'Rand (ZAR)'), ('MAD', 'Dirham (MAD)'), ('EGP', 'Livre égyptienne (EGP)'), ('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='XOF', max_length=3)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('logo_url', models.URLField(blank=True)),
                ('banner_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#6C5CE7', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #6C5CE7.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('social_facebook', models.CharField(blank=True, max_length=255)),
                ('social_instagram', models.CharField(blank=True, max_length=255)),
                ('social_tiktok', models.CharField(blank=True, max_length=255)),
                ('social_whatsapp', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('suspended', 'Suspendue')], default='draft', max_length=16)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro')], default='free', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('order_sequence', models.PositiveIntegerField(default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stores_store',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='stores_stor_status_d56e36_idx')],
            },
        ),
    ]
