# Generated by Django 5.0.9 on 2026-07-19 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.CharField(choices=[('counterfeit', 'Contrefaçon'), ('inappropriate', 'Contenu inapproprié'), ('misleading', 'Description trompeuse'), ('scam', 'Arnaque suspectée'), ('other', 'Autre')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examiné'), ('dismissed', 'Rejeté')], default='pending', max_length=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='products.product')),
            ],
            options={
                'db_table': 'products_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='products_re_status_77de85_idx')],
            },
        ),
    ]
